CREATE TABLE Categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(50)
);

CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    precio NUMBER,
    id_categoria NUMBER
);

INSERT INTO Categorias (nombre_categoria) VALUES ('Entradas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Sandwiches');
INSERT INTO Categorias (nombre_categoria) VALUES ('Ensaladas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Hamburguesas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Chorrillanas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Extras');
INSERT INTO Categorias (nombre_categoria) VALUES ('Postres');
INSERT INTO Categorias (nombre_categoria) VALUES ('Nuevos Sabores');
INSERT INTO Categorias (nombre_categoria) VALUES ('Cocktails Tematicos');
INSERT INTO Categorias (nombre_categoria) VALUES ('Cocktails Clasicos');
INSERT INTO Categorias (nombre_categoria) VALUES ('Tragos Clasicos');
INSERT INTO Categorias (nombre_categoria) VALUES ('Cervezas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Mocktails');
INSERT INTO Categorias (nombre_categoria) VALUES ('Bebidas');
INSERT INTO Categorias (nombre_categoria) VALUES ('Happy Hour');
INSERT INTO Categorias (nombre_categoria) VALUES ('Cafeteria');

INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Aros de Cebolla (14)', 6400, 1);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Chao Pescao!', 9500, 1);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Empanadas Camaron Queso', 8900, 1);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Mechada Queso', 11900, 2);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Mechada Agricola', 11900, 2);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Ensalada Clover', 8900, 3);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Proteina Pollo/Tofu/Seitan', 2000, 3);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Klask', 10900, 4);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Cola Cuerno', 11900, 4);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Forest Root', 11900, 4);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Paleo Rustica', 14900, 5);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Everdell', 14900, 5);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Papas Fritas Cheddar', 6700, 6);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Choco Frost Brownie', 7900, 7);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Honey Boy', 7490, 8);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Bola de Fuego', 8490, 9);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Herradura Mysterium', 13990, 9);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Whiskey Tiki', 8490, 9);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Pisco Sour Catan', 7990, 9);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Expresso Martini', 7490, 10);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Terremoto', 3990, 11);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Neskov Ipa', 5490, 12);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Rhino Hero', 7490, 13);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Limonada Sabrosa', 5490, 14);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Shop x2 (Happy Hour)', 8990, 15);
INSERT INTO Productos (nombre, precio, id_categoria) VALUES ('Chocolate Caliente Vegano', 5490, 16);

CREATE OR REPLACE PROCEDURE sp_RegistrarVenta (
    p_id_producto IN NUMBER,
    p_total IN NUMBER
) AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Venta registrada con éxito por un total de: ' || TO_CHAR(p_total));
END;
/
CREATE OR REPLACE PROCEDURE sp_ArqueoCaja AS
    v_total NUMBER;
BEGIN
    SELECT SUM(precio) INTO v_total FROM Productos;
    DBMS_OUTPUT.PUT_LINE('El total del arqueo es: ' || TO_CHAR(v_total));
END;
/